# Generated by Django 4.2.30 on 2026-09-15 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PitchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('pitch_type', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=255)),
                ('active_email', models.EmailField(max_length=254)),
                ('id_number', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
