# Generated by Django 6.1.1 on 2026-09-29 11:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_pitchendorsement_pitchreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num_volunteers_needed', models.SmallIntegerField(default=1)),
                ('status', models.CharField(default='open', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_requests', to='home.pitch')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_volunteers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerResponse',
            fields=[
                ('response_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_status', models.CharField(default='pending', max_length=30)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_responses', to=settings.AUTH_USER_MODEL)),
                ('volunteer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='home.volunteerrequest')),
            ],
        ),
    ]
